// Code generated by go-enum DO NOT EDIT.
// Version: -
// Revision: -
// Build Date: -
// Built By: -

package unifiedTime

const (
	// AnchorFirstMonthDay is a Anchor of type firstMonthDay.
	AnchorFirstMonthDay Anchor = "firstMonthDay"
	// AnchorFirstWeekDay is a Anchor of type firstWeekDay.
	AnchorFirstWeekDay Anchor = "firstWeekDay"
	// AnchorLastMonthDay is a Anchor of type lastMonthDay.
	AnchorLastMonthDay Anchor = "lastMonthDay"
	// AnchorLastWeekDay is a Anchor of type lastWeekDay.
	AnchorLastWeekDay Anchor = "lastWeekDay"
	// AnchorNextDay is a Anchor of type nextDay.
	AnchorNextDay Anchor = "nextDay"
	// AnchorPreviousDay is a Anchor of type previousDay.
	AnchorPreviousDay Anchor = "previousDay"
	// AnchorNextMonthFirstDay is a Anchor of type nextMonthFirstDay.
	AnchorNextMonthFirstDay Anchor = "nextMonthFirstDay"
	// AnchorFirstDayOfYear is a Anchor of type firstDayOfYear.
	AnchorFirstDayOfYear Anchor = "firstDayOfYear"
	// AnchorLastDayOfYear is a Anchor of type lastDayOfYear.
	AnchorLastDayOfYear Anchor = "lastDayOfYear"
)

func (e Anchor) Valid() bool {
	switch e {
	case AnchorFirstMonthDay,
		AnchorFirstWeekDay,
		AnchorLastMonthDay,
		AnchorLastWeekDay,
		AnchorNextDay,
		AnchorPreviousDay,
		AnchorNextMonthFirstDay,
		AnchorFirstDayOfYear,
		AnchorLastDayOfYear:
		return true
	}
	return false
}

func AllAnchorValues() []Anchor {
	return []Anchor{
		AnchorFirstMonthDay,
		AnchorFirstWeekDay,
		AnchorLastMonthDay,
		AnchorLastWeekDay,
		AnchorNextDay,
		AnchorPreviousDay,
		AnchorNextMonthFirstDay,
		AnchorFirstDayOfYear,
		AnchorLastDayOfYear,
	}
}

const (
	// RangeAnchorCurrentMonth is a RangeAnchor of type currentMonth.
	RangeAnchorCurrentMonth RangeAnchor = "currentMonth"
	// RangeAnchorPreviousMonth is a RangeAnchor of type previousMonth.
	RangeAnchorPreviousMonth RangeAnchor = "previousMonth"
	// RangeAnchorPastQuarter is a RangeAnchor of type pastQuarter.
	RangeAnchorPastQuarter RangeAnchor = "pastQuarter"
	// RangeAnchorPreviousYear is a RangeAnchor of type previousYear.
	RangeAnchorPreviousYear RangeAnchor = "previousYear"
)

func (e RangeAnchor) Valid() bool {
	switch e {
	case RangeAnchorCurrentMonth,
		RangeAnchorPreviousMonth,
		RangeAnchorPastQuarter,
		RangeAnchorPreviousYear:
		return true
	}
	return false
}

func AllRangeAnchorValues() []RangeAnchor {
	return []RangeAnchor{
		RangeAnchorCurrentMonth,
		RangeAnchorPreviousMonth,
		RangeAnchorPastQuarter,
		RangeAnchorPreviousYear,
	}
}

const (
	// RangeIntervalClosed is a RangeInterval of type closed.
	RangeIntervalClosed RangeInterval = "closed"
	// RangeIntervalOpen is a RangeInterval of type open.
	RangeIntervalOpen RangeInterval = "open"
	// RangeIntervalOpenStart is a RangeInterval of type openStart.
	RangeIntervalOpenStart RangeInterval = "openStart"
	// RangeIntervalOpenEnd is a RangeInterval of type openEnd.
	RangeIntervalOpenEnd RangeInterval = "openEnd"
)

func (e RangeInterval) Valid() bool {
	switch e {
	case RangeIntervalClosed,
		RangeIntervalOpen,
		RangeIntervalOpenStart,
		RangeIntervalOpenEnd:
		return true
	}
	return false
}

func AllRangeIntervalValues() []RangeInterval {
	return []RangeInterval{
		RangeIntervalClosed,
		RangeIntervalOpen,
		RangeIntervalOpenStart,
		RangeIntervalOpenEnd,
	}
}

const (
	// RelationBefore is a Relation of type before.
	RelationBefore Relation = "before"
	// RelationAfter is a Relation of type after.
	RelationAfter Relation = "after"
	// RelationIdentical is a Relation of type identical.
	RelationIdentical Relation = "identical"
	// RelationSameToYear is a Relation of type sameToYear.
	RelationSameToYear Relation = "sameToYear"
	// RelationSameToMonth is a Relation of type sameToMonth.
	RelationSameToMonth Relation = "sameToMonth"
	// RelationSameToDay is a Relation of type sameToDay.
	RelationSameToDay Relation = "sameToDay"
	// RelationSameToHour is a Relation of type sameToHour.
	RelationSameToHour Relation = "sameToHour"
	// RelationSameToMinute is a Relation of type sameToMinute.
	RelationSameToMinute Relation = "sameToMinute"
	// RelationSameToSecond is a Relation of type sameToSecond.
	RelationSameToSecond Relation = "sameToSecond"
	// RelationSameToMillisecond is a Relation of type sameToMillisecond.
	RelationSameToMillisecond Relation = "sameToMillisecond"
	// RelationSameToMillisecondFromEpoch is a Relation of type sameToMillisecondFromEpoch.
	RelationSameToMillisecondFromEpoch Relation = "sameToMillisecondFromEpoch"
	// RelationLeapYear is a Relation of type leapYear.
	RelationLeapYear Relation = "leapYear"
	// RelationInWeekend is a Relation of type inWeekend.
	RelationInWeekend Relation = "inWeekend"
)

func (e Relation) Valid() bool {
	switch e {
	case RelationBefore,
		RelationAfter,
		RelationIdentical,
		RelationSameToYear,
		RelationSameToMonth,
		RelationSameToDay,
		RelationSameToHour,
		RelationSameToMinute,
		RelationSameToSecond,
		RelationSameToMillisecond,
		RelationSameToMillisecondFromEpoch,
		RelationLeapYear,
		RelationInWeekend:
		return true
	}
	return false
}

func AllRelationValues() []Relation {
	return []Relation{
		RelationBefore,
		RelationAfter,
		RelationIdentical,
		RelationSameToYear,
		RelationSameToMonth,
		RelationSameToDay,
		RelationSameToHour,
		RelationSameToMinute,
		RelationSameToSecond,
		RelationSameToMillisecond,
		RelationSameToMillisecondFromEpoch,
		RelationLeapYear,
		RelationInWeekend,
	}
}

const (
	// TimePeriodDay is a TimePeriod of type day.
	TimePeriodDay TimePeriod = "day"
	// TimePeriodWeek is a TimePeriod of type week.
	TimePeriodWeek TimePeriod = "week"
	// TimePeriodMonth is a TimePeriod of type month.
	TimePeriodMonth TimePeriod = "month"
	// TimePeriodYear is a TimePeriod of type year.
	TimePeriodYear TimePeriod = "year"
)

func (e TimePeriod) Valid() bool {
	switch e {
	case TimePeriodDay,
		TimePeriodWeek,
		TimePeriodMonth,
		TimePeriodYear:
		return true
	}
	return false
}

func AllTimePeriodValues() []TimePeriod {
	return []TimePeriod{
		TimePeriodDay,
		TimePeriodWeek,
		TimePeriodMonth,
		TimePeriodYear,
	}
}

const (
	// TimeUnitYear is a TimeUnit of type year.
	TimeUnitYear TimeUnit = "year"
	// TimeUnitMonth is a TimeUnit of type month.
	TimeUnitMonth TimeUnit = "month"
	// TimeUnitDay is a TimeUnit of type day.
	TimeUnitDay TimeUnit = "day"
	// TimeUnitHour is a TimeUnit of type hour.
	TimeUnitHour TimeUnit = "hour"
	// TimeUnitMinute is a TimeUnit of type minute.
	TimeUnitMinute TimeUnit = "minute"
	// TimeUnitSecond is a TimeUnit of type second.
	TimeUnitSecond TimeUnit = "second"
	// TimeUnitMillisecond is a TimeUnit of type millisecond.
	TimeUnitMillisecond TimeUnit = "millisecond"
	// TimeUnitMicrosecond is a TimeUnit of type microsecond.
	TimeUnitMicrosecond TimeUnit = "microsecond"
)

func (e TimeUnit) Valid() bool {
	switch e {
	case TimeUnitYear,
		TimeUnitMonth,
		TimeUnitDay,
		TimeUnitHour,
		TimeUnitMinute,
		TimeUnitSecond,
		TimeUnitMillisecond,
		TimeUnitMicrosecond:
		return true
	}
	return false
}

func AllTimeUnitValues() []TimeUnit {
	return []TimeUnit{
		TimeUnitYear,
		TimeUnitMonth,
		TimeUnitDay,
		TimeUnitHour,
		TimeUnitMinute,
		TimeUnitSecond,
		TimeUnitMillisecond,
		TimeUnitMicrosecond,
	}
}

const (
	// TimeValueYear is a TimeValue of type year.
	TimeValueYear TimeValue = "year"
	// TimeValueMonth is a TimeValue of type month.
	TimeValueMonth TimeValue = "month"
	// TimeValueDay is a TimeValue of type day.
	TimeValueDay TimeValue = "day"
	// TimeValueHour is a TimeValue of type hour.
	TimeValueHour TimeValue = "hour"
	// TimeValueMinute is a TimeValue of type minute.
	TimeValueMinute TimeValue = "minute"
	// TimeValueSecond is a TimeValue of type second.
	TimeValueSecond TimeValue = "second"
	// TimeValueMillisecond is a TimeValue of type millisecond.
	TimeValueMillisecond TimeValue = "millisecond"
	// TimeValueMicrosecond is a TimeValue of type microsecond.
	TimeValueMicrosecond TimeValue = "microsecond"
	// TimeValueWeekday is a TimeValue of type weekday.
	TimeValueWeekday TimeValue = "weekday"
	// TimeValueWeekOfYear is a TimeValue of type weekOfYear.
	TimeValueWeekOfYear TimeValue = "weekOfYear"
	// TimeValueOrdinalDate is a TimeValue of type ordinalDate.
	TimeValueOrdinalDate TimeValue = "ordinalDate"
	// TimeValueMillisecondsSinceEpoch is a TimeValue of type millisecondsSinceEpoch.
	TimeValueMillisecondsSinceEpoch TimeValue = "millisecondsSinceEpoch"
	// TimeValueTimeZoneOffsetMilliseconds is a TimeValue of type timeZoneOffsetMilliseconds.
	TimeValueTimeZoneOffsetMilliseconds TimeValue = "timeZoneOffsetMilliseconds"
)

func (e TimeValue) Valid() bool {
	switch e {
	case TimeValueYear,
		TimeValueMonth,
		TimeValueDay,
		TimeValueHour,
		TimeValueMinute,
		TimeValueSecond,
		TimeValueMillisecond,
		TimeValueMicrosecond,
		TimeValueWeekday,
		TimeValueWeekOfYear,
		TimeValueOrdinalDate,
		TimeValueMillisecondsSinceEpoch,
		TimeValueTimeZoneOffsetMilliseconds:
		return true
	}
	return false
}

func AllTimeValueValues() []TimeValue {
	return []TimeValue{
		TimeValueYear,
		TimeValueMonth,
		TimeValueDay,
		TimeValueHour,
		TimeValueMinute,
		TimeValueSecond,
		TimeValueMillisecond,
		TimeValueMicrosecond,
		TimeValueWeekday,
		TimeValueWeekOfYear,
		TimeValueOrdinalDate,
		TimeValueMillisecondsSinceEpoch,
		TimeValueTimeZoneOffsetMilliseconds,
	}
}

const (
	// TruncationUnitToYear is a TruncationUnit of type toYear.
	TruncationUnitToYear TruncationUnit = "toYear"
	// TruncationUnitToMonth is a TruncationUnit of type toMonth.
	TruncationUnitToMonth TruncationUnit = "toMonth"
	// TruncationUnitToDay is a TruncationUnit of type toDay.
	TruncationUnitToDay TruncationUnit = "toDay"
	// TruncationUnitToHour is a TruncationUnit of type toHour.
	TruncationUnitToHour TruncationUnit = "toHour"
	// TruncationUnitToMinute is a TruncationUnit of type toMinute.
	TruncationUnitToMinute TruncationUnit = "toMinute"
	// TruncationUnitToSecond is a TruncationUnit of type toSecond.
	TruncationUnitToSecond TruncationUnit = "toSecond"
	// TruncationUnitToMillisecond is a TruncationUnit of type toMillisecond.
	TruncationUnitToMillisecond TruncationUnit = "toMillisecond"
)

func (e TruncationUnit) Valid() bool {
	switch e {
	case TruncationUnitToYear,
		TruncationUnitToMonth,
		TruncationUnitToDay,
		TruncationUnitToHour,
		TruncationUnitToMinute,
		TruncationUnitToSecond,
		TruncationUnitToMillisecond:
		return true
	}
	return false
}

func AllTruncationUnitValues() []TruncationUnit {
	return []TruncationUnit{
		TruncationUnitToYear,
		TruncationUnitToMonth,
		TruncationUnitToDay,
		TruncationUnitToHour,
		TruncationUnitToMinute,
		TruncationUnitToSecond,
		TruncationUnitToMillisecond,
	}
}

const (
	// WeekdayMonday is a Weekday of type monday.
	WeekdayMonday Weekday = "monday"
	// WeekdayTuesday is a Weekday of type tuesday.
	WeekdayTuesday Weekday = "tuesday"
	// WeekdayWednesday is a Weekday of type wednesday.
	WeekdayWednesday Weekday = "wednesday"
	// WeekdayThursday is a Weekday of type thursday.
	WeekdayThursday Weekday = "thursday"
	// WeekdayFriday is a Weekday of type friday.
	WeekdayFriday Weekday = "friday"
	// WeekdaySaturday is a Weekday of type saturday.
	WeekdaySaturday Weekday = "saturday"
	// WeekdaySunday is a Weekday of type sunday.
	WeekdaySunday Weekday = "sunday"
)

func (e Weekday) Valid() bool {
	switch e {
	case WeekdayMonday,
		WeekdayTuesday,
		WeekdayWednesday,
		WeekdayThursday,
		WeekdayFriday,
		WeekdaySaturday,
		WeekdaySunday:
		return true
	}
	return false
}

func AllWeekdayValues() []Weekday {
	return []Weekday{
		WeekdayMonday,
		WeekdayTuesday,
		WeekdayWednesday,
		WeekdayThursday,
		WeekdayFriday,
		WeekdaySaturday,
		WeekdaySunday,
	}
}
